services:
  web:
    build:
      context: Web
      additional_contexts:
        servicedefaults: ServiceDefaults
    ports:
      - "80:80"
    environment:
      - QUOTES_ENDPOINT=http://stocks:8082
      - TICKERS=MSFT AAPL GOOGL RKT.L
      - REDIS=redis
    depends_on:
      - stocks
      - redis
    x-azure:
      replicas: [2,6]
  stocks:
    build:
      context: QuoteService
    expose:
      - "8082"
  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    expose:
      - "6379"
    x-azure:
      ingress-type: tcp